### ISSUE TITLE
Orientation inconsistent with trajectory

### ISSUE THREAD

**Issue by manymuch** [ztsrxh/RSRD_dev_toolkit#1]
hi @ztsrxh ,
Thanks for the great work and make the code and data public. While dealing with the dataset, I am confused about the inconsistency between the rotation and translation.  
If I understand correctly, the pose info in ``loc_pose_vel.pkl`` contains translation(WGS84) and rotation(RPY) w.r.t the LiDAR.  
However, I found that the translation is not consistent with rotation in most cases, here is the minimum code to show:
```python
import pickle
import math


def lla_to_enu(C_lat, C_lon, C_alt, O_lat, O_lon, O_alt):
    '''
        Calculate the relative location with respect to the selected origin in the local ENU coordinate. unit: meter
        C_lat, C_lon, C_alt: current location
        O_lat, O_lon, O_alt: origin location
    '''

    Ea = 6378137
    Eb = 6356752.3142
    C_lat = math.radians(C_lat)
    C_lon = math.radians(C_lon)
    O_lat = math.radians(O_lat)
    O_lon = math.radians(O_lon)
    Ec = Ea * (1 - (Ea - Eb) / Ea * (math.sin(C_lat)) ** 2) + C_alt
    d_lat = C_lat - O_lat
    d_lon = C_lon - O_lon
    e = d_lon * Ec * math.cos(C_lat)
    n = d_lat * Ec
    u = C_alt - O_alt
    return e, n, u


if __name__ == "__main__":
    # change your path here
    file_path = 'rsrd-conti/2023-04-08-02-33-11-1-conti/loc_pose_vel.pkl'
    with open(file_path, 'rb') as f:
        loc_pose_vel = pickle.load(f)

    lat_origin = loc_pose_vel[0]["lat"]
    lon_origin = loc_pose_vel[0]["lon"]
    alt_origin = loc_pose_vel[0]["alt"]/1000  # mm --> m

    frame_idx = 0
    current_frame = loc_pose_vel[frame_idx]
    next_frame = loc_pose_vel[frame_idx + 1]
    e_current, n_current, u_current = lla_to_enu(
        current_frame["lat"], current_frame["lon"], current_frame["alt"]/1000, lat_origin, lon_origin, alt_origin)
    e_next, n_next, u_next = lla_to_enu(
        next_frame["lat"], next_frame["lon"], next_frame["alt"]/1000, lat_origin, lon_origin, alt_origin)
    e_diff = e_next - e_current
    n_diff = n_next - n_current

    print(f"e_diff, n_diff: {e_diff}, {n_diff}")  # point to south east
    print(f"vel_e, vel_n: {current_frame['vel_e']}, {current_frame['vel_n']}")  # point to south east
    print("yaw = ", current_frame["yaw"])  # point to north east
```
Output
```bash
e_diff, n_diff: 1.1044787519169914, -0.8783996584858526
vel_e, vel_n: 5522.0, -4463.0
yaw =  309.43
```
The e_diff, n_diff are consistent with vel_e, vel_n, inidicating that the vehicle is moving towards South East, according to this picture:
![image](https://github.com/ztsrxh/RSRD_dev_toolkit/assets/20460749/23b056b9-f23d-49b3-9b71-f6abe800b33e)
If the vehicle's head is towards **SouthEast**, the Y axis of the LiDAR should be towards North West.

While the Yaw angle = 309.43 degree shows that the vehicle is pointing to **NorthEast** according to this picture:
![image](https://github.com/ztsrxh/RSRD_dev_toolkit/assets/20460749/5f9d3f7e-e785-479e-9984-e728329a074c)

**Comment by ztsrxh** [comment]
Thanks for your detailed review. We got the rotation direction wrong. We now have updated the datasets and corresponding yaw definition. The correct version is available for downloading now. If you find problems or have questions when using, feel free to contact us.
Thanks very much!
