### ISSUE TITLE
请问你们具体是怎么在RSRD-dense上训练ACVNet的呢？

### ISSUE THREAD

**Issue by slasher233** [ztsrxh/RSRD_dev_toolkit#2]
论文中只写了max disparity设置为128，训练了5个epoch；但我训练得到的EPE始终保持在1.34-1.36，和论文里的0.354相差有些远，请问可以提供一下你们的优化器、学习率下降策略、图像预处理方法吗？
目前我是采用的Adam优化器，学习率为0.001，图像被resize到1/4分辨率后，使用mean=0.5, std=0.5的标准化

**Comment by ztsrxh** [comment]
输入的是半分辨率（960*540）的图像，不是1/4, 最大视差为64，不是128。 数据输入部分请参考我们DVANet的code。LR scheduler 是OneCycleLR。其他都是ACVNet的默认配置。
